---
- name: Install HTTP server
  hosts: n2
  become: yes

  tasks:
  - name: Install Apache2
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - name: Start and enable Apache2 service
    service:
      name: apache2
      state: started
      enabled: yes    
...      