---
- name: variable Demo
  hosts: g1
  become: yes
  vars:
    myusername: Modeks

  tasks:
  - name: update dynamic page
    template:
      src: dynamic.j2
      dest: /var/www/html/dynamic.html
...   